# Generated by Django 5.0 on 2023-12-25 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='owner',
            new_name='file_owner',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='owner',
            new_name='folder_owner',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.SlugField(default='yes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
