# Generated by Django 5.0 on 2023-12-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_folder_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='decrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='decryption_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
